application: feed--me
version: 3
runtime: go
api_version: go1

handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /refreshAll
  script: _go_app
  login: admin
- url: /refresh
  script: _go_app
- url: /.*
  script: _go_app
  login: required
